### model
# model_name_or_path: Qwen/Qwen2.5-7B-Instruct
# adapter_name_or_path: results/llama3-8b/lora/sft

### method
# stage: sft
# do_predict: true
finetuning_type: lora

### dataset
# task: mmlucot_n1000
task_dir: evaluation
template: fewshot
lang: en
cutoff_len: 32768 # Max position embeddings for Qwen2.5
max_samples: 100000
# n_shot: 5

### output
# overwrite_output_dir: true
# save_dir: results/llama3-8b/lora/eval

### eval
batch_size: 1