### model
# model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_rank: 128
# lora_target: q_proj,k_proj

### dataset
# dataset: mmlu_train_cot_s0
template: qwen
cutoff_len: 32768 # Max position embeddings for Qwen2.5
max_samples: 100000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
logging_steps: 10
save_steps: 20
plot_loss: true
# overwrite_output_dir: false
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 10
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null