model_name_or_path: Qwen/Qwen2.5-7B-Instruct
# adapter_name_or_path: saves/llama3-8b/lora/sft

### method
# stage: sft
# do_predict: true
finetuning_type: lora

# ### dataset
# eval_dataset: mmlu_test_s0
# template: qwen
# cutoff_len: 2048
# max_samples: 50
# overwrite_cache: true
# preprocessing_num_workers: 16

# ### output
# overwrite_output_dir: true

# ### eval
# per_device_eval_batch_size: 1
# predict_with_generate: true
# ddp_timeout: 180000000


task: mmlu_test # mmlu_test, ceval_validation, cmmlu_test
task_dir: evaluation-custom
template: fewshot
lang: en
max_samples: 10000
# n_shot: 5


### output
# save_dir: saves/llama3-8b/lora/eval

### eval
batch_size: 1